### ISSUE TITLE
error in subscribe example

### ISSUE THREAD

**Issue by medilies** [php-mqtt/client#4]
i got the same error after many tests (maybe 10).
each test duration was between 30s and 90s while receiving messages (1 to 9 messages)!
ps: if not receiving any no problems happens!

**code**
```
<?php
use PhpMqtt\Client\MQTTClient;
require "vendor/autoload.php";

$server = 'localhost';
$port = '1883';
$clientId = 'test-subscriber';

$mqtt = new MQTTClient($server, $port, $clientId);
$mqtt->connect();
$mqtt->subscribe('php-client-sub', function ($topic, $message) {
    echo sprintf("Received message on topic [%s]: %s\n", $topic, $message);
}, 0);
$mqtt->loop(true);
```

**error message**
```
PHP Fatal error:  Uncaught PhpMqtt\Client\Exceptions\DataTransferException: [65] Transfering data over socket failed: Sending data over the socket failed. Has it been closed? in C:\xampp\htdocs\demo\mqtt_sub\vendor\php-mqtt\client\src\MQTTClient.php:1305
Stack trace:
#0 C:\xampp\htdocs\demo\mqtt_sub\vendor\php-mqtt\client\src\MQTTClient.php(349): PhpMqtt\Client\MQTTClient->writeToSocket('\xC0\x00')
#1 C:\xampp\htdocs\demo\mqtt_sub\vendor\php-mqtt\client\src\MQTTClient.php(670): PhpMqtt\Client\MQTTClient->ping()
#2 C:\xampp\htdocs\demo\mqtt_sub\index.php(14): PhpMqtt\Client\MQTTClient->loop(true)
#3 {main}
  thrown in C:\xampp\htdocs\demo\mqtt_sub\vendor\php-mqtt\client\src\MQTTClient.php on line 1305

Fatal error: Uncaught PhpMqtt\Client\Exceptions\DataTransferException: [65] Transfering data over socket failed: Sending data over the socket failed. Has it been closed? in C:\xampp\htdocs\demo\mqtt_sub\vendor\php-mqtt\client\src\MQTTClient.php on line 1305

PhpMqtt\Client\Exceptions\DataTransferException: [65] Transfering data over socket failed: Sending data over the socket failed. Has it been closed? in C:\xampp\htdocs\demo\mqtt_sub\vendor\php-mqtt\client\src\MQTTClient.php on line 1305

Call Stack:
    0.3939     398400   1. {main}() C:\xampp\htdocs\demo\mqtt_sub\index.php:0
    0.4084     840928   2. PhpMqtt\Client\MQTTClient->loop() C:\xampp\htdocs\demo\mqtt_sub\index.php:14
   24.4518     843288   3. PhpMqtt\Client\MQTTClient->ping() C:\xampp\htdocs\demo\mqtt_sub\vendor\php-mqtt\client\src\MQTTClient.php:670
   24.4519     843320   4. PhpMqtt\Client\MQTTClient->writeToSocket() C:\xampp\htdocs\demo\mqtt_sub\vendor\php-mqtt\client\src\MQTTClient.php:349
```

**Comment by Namoshek** [comment]
Not sure what could be happening here. What data are you receiving? The only reasons I can see would be that either the socket has been closed (e.g. by the broker) or, for some reason (e.g. bad connection), not all data could be sent (which is only 2 byte in case of a ping and therefore extremely unlikely).

**Comment by medilies** [comment]
I tried to send only one digit numbers many times.

not sure if it is a network issue, because all the setup is on localhost:
MQTTBox
mosquitto broker
php script

**Comment by Namoshek** [comment]
What exactly is _many times_? Can you please use the examples from [php-mqtt/client-examples](https://github.com/php-mqtt/client-examples) and see if the problem still occurs? You might want to increase the number of messages in the `publish.php`.

Anyhow, it is not unrealistic that you overloaded the client. It is not meant to process thousands of messages per second.

**Comment by medilies** [comment]
here is a more cleare illustration for _many times_
**publishing script:**
```
<?php
use PhpMqtt\Client\MQTTClient;
require "vendor/autoload.php";

$server = 'localhost';
$port = '1883';
$clientId = 'test-subscriber';

$mqtt = new MQTTClient($server, $port, $clientId);
$mqtt->connect();
$mqtt->subscribe('yo', function ($topic, $message) {
    echo sprintf("Received message on topic [%s]: %s\n", $topic, $message);
}, 0);
$mqtt->loop(true);
```
I also tried this script with sleep(1), sleep(3) and sleep(10)

**subscription script:**
```
<?php
use PhpMqtt\Client\MQTTClient;
require "vendor/autoload.php";

$server = 'localhost';
$port = '1883';
$clientId = 'test-subscriber';

$mqtt = new MQTTClient($server, $port, $clientId);
$mqtt->connect();
$mqtt->subscribe('yo', function ($topic, $message) {
    echo sprintf("Received message on topic [%s]: %s\n", $topic, $message);
}, 0);
$mqtt->loop(true);
```
**shell for sub:**
```
php index.php
Received message on topic [yo]: 1
Received message on topic [yo]: 2
Received message on topic [yo]: 3
PHP Fatal error:  Uncaught PhpMqtt\Client\Exceptions\DataTransferException: [65] Transfering data over socket failed: Sending data over the socket failed. Has it been closed? in C:\xampp\htdocs\demo\mqtt_sub\vendor\php-mqtt\client\src\MQTTClient.php:1305
Stack trace:
#0 C:\xampp\htdocs\demo\mqtt_sub\vendor\php-mqtt\client\src\MQTTClient.php(349): PhpMqtt\Client\MQTTClient->writeToSocket('\xC0\x00')
#1 C:\xampp\htdocs\demo\mqtt_sub\vendor\php-mqtt\client\src\MQTTClient.php(670): PhpMqtt\Client\MQTTClient->ping()
#2 C:\xampp\htdocs\demo\mqtt_sub\index.php(14): PhpMqtt\Client\MQTTClient->loop(true)
#3 {main}
  thrown in C:\xampp\htdocs\demo\mqtt_sub\vendor\php-mqtt\client\src\MQTTClient.php on line 1305

Fatal error: Uncaught PhpMqtt\Client\Exceptions\DataTransferException: [65] Transfering data over socket failed: Sending data over the socket failed. Has it been closed? in C:\xampp\htdocs\demo\mqtt_sub\vendor\php-mqtt\client\src\MQTTClient.php on line 1305

PhpMqtt\Client\Exceptions\DataTransferException: [65] Transfering data over socket failed: Sending data over the socket failed. Has it been closed? in C:\xampp\htdocs\demo\mqtt_sub\vendor\php-mqtt\client\src\MQTTClient.php on line 1305

Call Stack:
    0.4030     399544   1. {main}() C:\xampp\htdocs\demo\mqtt_sub\index.php:0
    0.4185     842056   2. PhpMqtt\Client\MQTTClient->loop() C:\xampp\htdocs\demo\mqtt_sub\index.php:14
   34.8331     844416   3. PhpMqtt\Client\MQTTClient->ping() C:\xampp\htdocs\demo\mqtt_sub\vendor\php-mqtt\client\src\MQTTClient.php:670
   34.8331     844448   4. PhpMqtt\Client\MQTTClient->writeToSocket() C:\xampp\htdocs\demo\mqtt_sub\vendor\php-mqtt\client\src\MQTTClient.php:349
```
-----------------------------------------------------------
anyway apparently the [example ](https://github.com/php-mqtt/client-examples)isn't suitable for running under windows
```
"require": {
        "ext-pcntl": "*",
        "php-mqtt/client": "^0.1"
    }
```
**shell report:**
```
composer install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested PHP extension ext-pcntl * is missing from your system. Install or enable PHP's pcntl extension.
```

> Note: This [extension](https://www.php.net/manual/en/intro.pcntl.php) is not available on Windows platforms.

**Comment by Namoshek** [comment]
Yeah, the example is using signal handlers for a clean shutdown and requires therefore the `pcntl` extension. You can install the composer dependencies with `--ignore-platform-reqs` and remove the signal handling from the `subscribe.php` though (all method calls starting with `pcntl`). Signal handling is only there for demonstration purposes; if you kill the script, open sockets are closed anyway.

To your problem: you have posted the subscribe script twice, I guess by accident. I just retried running my own examples using Mosquitto though. And interestingly, they do not work. Not sure if it is because of the public test server or something else. I always use HiveMQ to be honest and have never tried the client with any other broker before.

Running the examples with the logger at level `DEBUG` I noticed the following though:
```
[debug] Sending ping to the MQTT broker to keep the connection alive. ({"broker":"test.mosquitto.org:1883"})
[debug] Sending ping to the MQTT broker to keep the connection alive. ({"broker":"test.mosquitto.org:1883"})
[debug] Sending ping to the MQTT broker to keep the connection alive. ({"broker":"test.mosquitto.org:1883"})
[debug] Sending ping to the MQTT broker to keep the connection alive. ({"broker":"test.mosquitto.org:1883"})
[debug] Sending ping to the MQTT broker to keep the connection alive. ({"broker":"test.mosquitto.org:1883"})
[debug] Re-publishing pending messages to MQTT broker. ({"broker":"test.mosquitto.org:1883"})
[debug] Re-sending pending unsubscribe requests to MQTT broker. ({"broker":"test.mosquitto.org:1883"})
[debug] Sending ping to the MQTT broker to keep the connection alive. ({"broker":"test.mosquitto.org:1883"})
[debug] Sending ping to the MQTT broker to keep the connection alive. ({"broker":"test.mosquitto.org:1883"})
[debug] Received ping acknowledgement from an MQTT broker. ({"broker":"test.mosquitto.org:1883"})
[debug] Received ping acknowledgement from an MQTT broker. ({"broker":"test.mosquitto.org:1883"})
[debug] Received ping acknowledgement from an MQTT broker. ({"broker":"test.mosquitto.org:1883"})
[debug] Received ping acknowledgement from an MQTT broker. ({"broker":"test.mosquitto.org:1883"})
[debug] Received ping acknowledgement from an MQTT broker. ({"broker":"test.mosquitto.org:1883"})
[debug] Received ping acknowledgement from an MQTT broker. ({"broker":"test.mosquitto.org:1883"})
[debug] Received ping acknowledgement from an MQTT broker. ({"broker":"test.mosquitto.org:1883"})
```
I guess that means the server is not able to answer before the client resends the ping. Not sure if that is something a broker may dislike (especially since all pings contain the same message id and are literally duplicates).

To investigate further, I suggest you try running your script against HiveMQ (e.g. using the public test server `broker.hivemq.com:1883`). If that fails as well, and you also tried my examples, I'm a bit out of ideas.

**Comment by medilies** [comment]
well I'll try hiveMQ broker just for testing. because using an external broker doesn't suit my actual project.

many thanks for your responses and I hope you good luck with this project.
