### ISSUE TITLE
PHP "Establishing connection to MQTT failed"

### ISSUE THREAD

**Issue by abdulmoeed137** [php-mqtt/client#72]
Fatal error: Uncaught PhpMqtt\Client\Exceptions\ConnectingToBrokerFailedException: [1] Establishing a connection to the MQTT broker failed: Connection closed without reason. in /home/forge/mqtt.spidertech.dev/public/vendor/php-mqtt/client/src/MQTTClient.php:458 Stack trace: #0 /home/forge/mqtt.spidertech.dev/public/vendor/php-mqtt/client/src/MQTTClient.php(147): PhpMqtt\Client\MQTTClient->performConnectionHandshake() #1 /home/forge/mqtt.spidertech.dev/public/index.php(11): PhpMqtt\Client\MQTTClient->connect() #2 {main} thrown in /home/forge/mqtt.spidertech.dev/public/vendor/php-mqtt/client/src/MQTTClient.php on line 458

**Comment by Namoshek** [comment]
You should give a bit more background and code if you want some help. An exception alone is not sufficient. Could be anything from a closed firewall to a misconfigured client, proxy or broker.

**Comment by abdulmoeed137** [comment]
this is my PHP file code 

<?php

require 'vendor/autoload.php';

use PhpMqtt\Client\MQTTClient;

$server   = 'mqtt.flespi.io:443';
$port     = 443;
$clientId = 'aa2233';
$mqtt = new MqttClient($server, $port, $clientId);
$mqtt->connect();


?>

**Comment by Namoshek** [comment]
Why do you provide the port twice? It does not work as part of the hostname.

**Comment by abdulmoeed137** [comment]
updated 
`<?php

require 'vendor/autoload.php';

use PhpMqtt\Client\MQTTClient;

$server   = 'mqtt.flespi.io';
$port     = 443;
$clientId = 'aa2233';
$mqtt = new MqttClient($server, $port, $clientId);
$mqtt->connect();


?>`

Error : 

Fatal error: Uncaught PhpMqtt\Client\Exceptions\ConnectingToBrokerFailedException: [1] Establishing a connection to the MQTT broker failed: Connection closed without reason. in /home/forge/mqtt.spidertech.dev/public/vendor/php-mqtt/client/src/MQTTClient.php:458 Stack trace: #0 /home/forge/mqtt.spidertech.dev/public/vendor/php-mqtt/client/src/MQTTClient.php(147): PhpMqtt\Client\MQTTClient->performConnectionHandshake() #1 /home/forge/mqtt.spidertech.dev/public/index.php(11): PhpMqtt\Client\MQTTClient->connect() #2 {main} thrown in /home/forge/mqtt.spidertech.dev/public/vendor/php-mqtt/client/src/MQTTClient.php on line 458

**Comment by Namoshek** [comment]
You need to provide `ConnectionSettings` to the `connect($settings)` method, which enable TLS for the connection (since you are using Port 443, I want to use TLS).

```php
<?php

require 'vendor/autoload.php';

use PhpMqtt\Client\MqttClient;
use PhpMqtt\Client\ConnectionSettings;

$server   = 'mqtt.flespi.io';
$port     = 443;
$clientId = 'aa2233';
$mqtt = new MqttClient($server, $port, $clientId);
$connectionSettings = (new ConnectionSettings)
    ->setUseTls(true)
    ->setTlsSelfSignedAllowed(true);
$mqtt->connect($connectionSettings);
```

**Comment by thg2k** [comment]
Maybe try port 1883 or 8883. Mqtt over websocket is not supposed by this library yet?

**Comment by Namoshek** [comment]
Closing this due to inactivity and wrong usage.
